learningt/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('relative/',views.relative,name = 'relative'),
    path('other/', views.other, name = 'other'),

]

learningt/learningt/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
urlpatterns = [
    path('',views.index, name = "index"),
    path("admin/", admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
]

learningt/basicapp/models.py
from django.db import models

# Create your models here.

learningt/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    rushi_dict = {'text':'heyy all', 'number':99 }
    return render(request,'basicapp/index.html',rushi_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_templates.html')

learningt/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class = "navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href = "{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href = "{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="navbar-link" href = "{%url 'basicapp:other' %}">OTHER</a></li>
        </ul>
      </div>
   </nav>

   <div class="container">

     {% block body_block %}

     {% endblock %}

   </div>

  </body>
</html>

learningt/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h1>THIS  IS  INDEX.HTML</h1>
    <h1>{{ text|cut:'heyy' }}</h1>
    <h1>{{ number|add:"101" }}</h1>
  {% endblock %}

learningt/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}

    <h1>THIS IS OTHER.HTML</h1>
    <h2>This is an example of template inheritance! </h2>
    {% endblock %}

learningt/templates/basicapp/relative_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>
    <h1>THIS IS RELATIVE.HTML</h1>
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index' %}">LINK TO INDEX</a>
  </body>
</html>